kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kcd-kochi-2026
nodes:
  - role: control-plane
    image: kindest/node:v1.35.0
  - role: worker
    image: kindest/node:v1.35.0
    labels:
      instance-type: spot
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        taints:
        - key: instance-type
          value: spot
          effect: NoSchedule
  - role: worker
    image: kindest/node:v1.35.0
    labels:
      instance-type: on-demand
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        taints:
        - key: instance-type
          value: on-demand
          effect: NoSchedule
  - role: worker
    image: kindest/node:v1.35.0