apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-rgd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-apps
    repoURL: https://github.com/sayed-imran/kcd-kochi-2026.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true